version: '3.8'
services:
  web:
    build:
     context: .
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    depends_on:
    - redis

  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    volumes:
    - redis_try_v:/data

volumes:
  redis_try_v:

