version: '3.8'
services:
  web:
    build:
     context: .
      
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    depends_on:
    - redis
  worker:
    build:
     context: .
    command: rq worker --url redis://redis:6379
    depends_on:
    - web
    - redis 

  redis:
    image: redis/redis-stack-server
    ports:
    - '6379:6379'